#!/usr/bin/env python3
"""render_standards — render the standards SSOT-YAML tree into a human-readable
code-standards.md digest.

ONE direction only: SSOT -> view. The renderer never edits the SSOT; the digest
is the secondary representation so prose is authored once (in the .std.yaml
source) and the markdown view is generated. This removes the double-maintenance
of the old format, where the same prose lived in both frontmatter and body.

Deterministic: areas/rule-groups/rules are sorted by id, there is no timestamp
and no randomness, so re-rendering the same tree is byte-identical (idempotent).
A generated-marker header tells an editor to change the SSOT, not the digest.

CLI:
    render_standards.py --root <project-dir> --out <path> [--force] [--check]
        --out    REQUIRED. No implicit default: rendering an empty tree over a
                 hand-authored file would silently wipe it.
        --force  overwrite an existing --out file that lacks the generated-marker
                 (a hand-authored file); without it, the write is refused.
        --check  render in memory and diff against the existing --out file; exit 1
                 on any drift (use as a CI gate), 0 if identical. Never writes.
"""

import argparse
import sys
from pathlib import Path
from typing import Any, Dict, List

import standards_graph
from encoding_utils import configure_utf8_console

configure_utf8_console()


GENERATED_MARKER = (
    "<!-- generated by render_standards.py — edit the SSOT "
    "(harness/standards/*.std.yaml), not this file -->"
)


def _prose_block(text: Any) -> List[str]:
    """Return the prose lines for a description/rationale field, stripped of
    trailing whitespace. A missing/blank field yields no lines."""
    if not isinstance(text, str):
        return []
    stripped = text.strip()
    return [stripped] if stripped else []


def _render_check(chk: Any) -> str:
    """Human-readable form of a compliance_check for the digest. A type-1 shell
    check is a mapping `{type, cmd}` — render its `cmd` (or `text`/`type`) rather
    than leaking a raw Python dict repr into the markdown."""
    if isinstance(chk, dict):
        return str(chk.get("cmd") or chk.get("text") or chk.get("type") or "")
    return str(chk)


def _nodes_by_type(graph: Dict[str, Any], node_type: str) -> List[Dict[str, Any]]:
    return sorted(
        (n for n in graph["nodes"] if n.get("type") == node_type),
        key=lambda n: n.get("id") or "",
    )


def _render_detector(det: Any) -> str:
    """Human-readable form of a rule detector for the checklist. A mapping
    detector renders its pattern/cmd/type, never a raw Python dict repr."""
    if isinstance(det, dict):
        return str(det.get("pattern") or det.get("cmd") or det.get("type") or "")
    return str(det)


def render_graph(graph: Dict[str, Any]) -> str:
    """Render a built standards graph to the markdown digest string."""
    lines: List[str] = [
        "# Code Standards (generated digest)",
        "",
        GENERATED_MARKER,
        "",
        "Single source of truth: `harness/standards/*.std.yaml`. This file is a "
        "rendered view — regenerate with `render_standards.py`; do not edit by hand.",
        "",
    ]

    # Charter digest carries ONLY charter-zone areas; the operational zone is
    # rendered separately (render_operational) and never mixed in here (H2).
    areas = [a for a in _nodes_by_type(graph, "std_area")
             if a.get("zone") != "operational"]
    rule_groups = _nodes_by_type(graph, "rule_group")
    rules = _nodes_by_type(graph, "rule")

    if not areas:
        lines.append("_No standard areas defined yet._")
        lines.append("")
        return "\n".join(lines) + "\n"

    for area in areas:
        title = area.get("title") or area.get("id")
        lines.append(f"## {title}")
        lines.append("")
        for p in _prose_block(area.get("description")):
            lines.append(p)
            lines.append("")

        area_groups = [rg for rg in rule_groups if rg.get("std_area") == area.get("id")]
        for rg in area_groups:
            rg_title = rg.get("title") or rg.get("id")
            lines.append(f"### {rg_title}")
            lines.append("")
            for p in _prose_block(rg.get("description")):
                lines.append(p)
                lines.append("")

            rg_rules = [r for r in rules if r.get("rule_group") == rg.get("id")]
            for r in rg_rules:
                rid = r.get("id")
                rtitle = r.get("title") or ""
                lines.append(f"- **{rid}** — {rtitle}".rstrip())
                for chk in r.get("compliance_checks") or []:
                    lines.append(f"  - check: {_render_check(chk)}")
                for p in _prose_block(r.get("rationale")):
                    lines.append(f"  - rationale: {p}")
            lines.append("")

    # Collapse a trailing run of blank lines to exactly one terminating newline.
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def render_operational(graph: Dict[str, Any]) -> str:
    """Render the operational-zone rule-leaves into a per-language review
    checklist (the H2 counterpart to the charter digest).

    Grouped by the language inferred from each rule's scope, sorted by language
    then rule id — deterministic, no timestamp, so re-rendering is byte-identical
    and `--check` can gate drift. Disabled rules (enabled:false) are omitted.
    """
    lines: List[str] = [
        "# Review Checklist (generated digest)",
        "",
        GENERATED_MARKER,
        "",
        "Single source of truth: `harness/standards/*.std.yaml` (operational "
        "zone). This file is a rendered view — regenerate with "
        "`render_standards.py --kind operational`; do not edit by hand.",
        "",
    ]

    areas = [a for a in _nodes_by_type(graph, "std_area")
             if a.get("zone") == "operational"]
    if not areas:
        lines.append("_No operational standards defined yet._")
        lines.append("")
        return "\n".join(lines) + "\n"

    area_ids = {a.get("id") for a in areas}
    rg_ids = {rg.get("id") for rg in _nodes_by_type(graph, "rule_group")
              if rg.get("std_area") in area_ids}
    op_rules = [r for r in _nodes_by_type(graph, "rule")
                if r.get("rule_group") in rg_ids and r.get("enabled") is not False]

    by_lang: Dict[str, List[Dict[str, Any]]] = {}
    for r in op_rules:
        by_lang.setdefault(
            standards_graph.lang_from_scope(r.get("scope")), []).append(r)

    for lang in sorted(by_lang):
        lines.append(f"## {lang}")
        lines.append("")
        for r in sorted(by_lang[lang], key=lambda n: n.get("id") or ""):
            rid = r.get("id")
            rtitle = r.get("title") or ""
            sev = r.get("severity") or "info"
            floor = " [floor]" if r.get("floor") else ""
            lines.append(f"- **{rid}** ({sev}){floor} — {rtitle}".rstrip())
            scope = r.get("scope") or []
            if scope:
                lines.append(f"  - scope: {', '.join(scope)}")
            det = r.get("detector")
            if det:
                lines.append(f"  - detector: {_render_detector(det)}")
            for p in _prose_block(r.get("rationale")):
                lines.append(f"  - rationale: {p}")
        lines.append("")

    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def render_root(root: Path, kind: str = "charter") -> str:
    """Build the standards graph under `root` and render the requested digest:
    `charter` (the code-standards digest) or `operational` (the review
    checklist)."""
    graph = standards_graph.build_graph(Path(root))
    if kind == "operational":
        return render_operational(graph)
    return render_graph(graph)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".", help="project root (contains harness/standards/)")
    ap.add_argument("--out", default=None,
                    help="REQUIRED output path for the rendered digest")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an --out file that lacks the generated-marker")
    ap.add_argument("--check", action="store_true",
                    help="diff rendered output against --out; exit 1 on drift, never write")
    ap.add_argument("--kind", choices=("charter", "operational"), default="charter",
                    help="which digest to render: charter (default) or the "
                         "operational review checklist")
    args = ap.parse_args(argv)

    if not args.out:
        sys.stderr.write(
            "error: --out is required (no default — rendering over a hand-authored "
            "file would wipe it)\n")
        return 2

    root = Path(args.root).resolve()
    out_path = Path(args.out)
    if out_path.is_dir():
        sys.stderr.write("error: --out is a directory: %s\n" % out_path)
        return 2
    rendered = render_root(root, kind=args.kind)

    if args.check:
        if not out_path.exists():
            sys.stderr.write("error: --check target does not exist: %s\n" % out_path)
            return 1
        current = out_path.read_text(encoding="utf-8")
        if current != rendered:
            sys.stderr.write("drift: %s is out of date — re-render from the SSOT\n" % out_path)
            return 1
        return 0

    # no-clobber: refuse to overwrite a file that is NOT a prior render (no
    # generated-marker) unless --force, so a hand-authored standards file is
    # never silently replaced by a render of an empty/partial tree.
    if out_path.exists() and not args.force:
        existing = out_path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in existing:
            sys.stderr.write(
                "error: %s exists and is not a generated digest (no marker); "
                "pass --force to overwrite\n" % out_path)
            return 2

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")
    sys.stdout.write(str(out_path) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
