"""P4 — standalone default-theme gate.

Builds a minimal 2-page site using ONLY assets from default-theme/assets/
(no overlay, no domain JS/CSS).  Asserts:

  1. index.html and pages/*.html are written (non-empty).
  2. index.html contains canvas#net (hero shell), btn-en, btn-vi (lang-toggle),
     and the sidebar element (.docs-side).
  3. No @key@ dangling tokens remain in any output HTML file.
  4. Every <script src> and <link href> referencing assets/ resolves to a file
     that exists in public/assets/.

Proves: a project with no custom design still gets a working showcase shell.
"""
import base64
import pathlib
import re
import sys
import tempfile

import pytest

# ---- path wiring: ssg_engine lives in scripts/ ----
_SKILL = pathlib.Path(__file__).resolve().parents[1]
_SCRIPTS = _SKILL / "scripts"
_DEFAULT_THEME_ASSETS = _SKILL / "default-theme" / "assets"
sys.path.insert(0, str(_SCRIPTS))
import ssg_engine as engine  # noqa: E402


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_ATKEY_RE = re.compile(r"@[a-z0-9-]+@")
_SCRIPT_SRC_RE = re.compile(r'<script\s+src="([^"]+)"')
_LINK_HREF_RE = re.compile(r'<link\s[^>]*href="([^"]+)"')


def _build_minimal_ctx(out_dir: pathlib.Path, theme_assets: pathlib.Path,
                        partials_dir: pathlib.Path) -> engine.Ctx:
    """Build a Ctx with shell-only assets from default-theme, 2 empty pages."""
    _FAVICON_SVG = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">'
                    '<rect width="32" height="32" rx="7" fill="#070b16"/>'
                    '<circle cx="16" cy="16" r="7" fill="#38bdf8"/></svg>')
    favicon = "data:image/svg+xml;base64," + base64.b64encode(
        _FAVICON_SVG.encode("utf-8")).decode("ascii")

    # Shell-only asset slots (no domain parts)
    js_parts = ["01-core-shell.js"]
    css_parts = ["01-base.css", "02-components.css", "05-layout.css", "06-print-a11y.css"]
    vendor = ["three.min.js"]

    def _assemble(subdir: str, parts: list[str]) -> str:
        """Concatenate parts from default-theme assets."""
        chunks = []
        for p in parts:
            fp = theme_assets / subdir / p
            chunks.append(fp.read_text(encoding="utf-8"))
        return "".join(chunks)

    pages = [
        ("hub", "Overview", "Tổng quan", "hub.html", "My Project", "#38bdf8", True),
        ("intro", "Introduction", "Giới thiệu", "intro.html", "Intro", "#34d399", True),
    ]
    categories = [
        ("main", "Content", "Nội dung", ["intro"]),
    ]
    footer_pages = [("hub", "Tổng quan", "Overview"), ("intro", "Giới thiệu", "Introduction")]

    return engine.Ctx(
        pages=pages,
        categories=categories,
        page_index={p[0]: p for p in pages},
        css=_assemble("css", css_parts),
        js=_assemble("js", js_parts),
        vendor=vendor,
        assets_dir=theme_assets,
        partials_dir=partials_dir,
        footer_pages=footer_pages,
        brand_html="My&nbsp;Project",
        brand_name="My Project",
        desc="A standalone showcase built with default-theme only.",
        favicon=favicon,
        lang_storage_key="my-lang",
        gen_banner="<!-- GENERATED by test_default_theme_standalone -->",
        chrome_html='<div class="glow g1"></div><div class="glow g2"></div>'
                    '<div class="glow g3"></div>\n<canvas id="net"></canvas>',
    )


def _make_partials(tmp: pathlib.Path) -> pathlib.Path:
    """Create a minimal partials dir with a generic _footer.html."""
    partials = tmp / "partials"
    partials.mkdir()
    (partials / "_footer.html").write_text(
        '<footer><div class="foot-in">'
        '<div><div class="brand">My Project</div></div>'
        '<div><h4>Pages</h4>{FOOTER_LINKS}</div>'
        '</div></footer>',
        encoding="utf-8",
    )
    return partials


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def test_default_theme_standalone_build():
    """Full standalone build: gate asserts listed in module docstring."""
    # Verify default-theme assets exist before attempting the build
    assert _DEFAULT_THEME_ASSETS.is_dir(), (
        f"default-theme/assets/ not found at {_DEFAULT_THEME_ASSETS}"
    )
    assert (_DEFAULT_THEME_ASSETS / "js" / "01-core-shell.js").is_file(), (
        "default-theme/assets/js/01-core-shell.js missing"
    )
    for css in ("01-base.css", "02-components.css", "05-layout.css", "06-print-a11y.css"):
        assert (_DEFAULT_THEME_ASSETS / "css" / css).is_file(), (
            f"default-theme/assets/css/{css} missing"
        )
    assert (_DEFAULT_THEME_ASSETS / "lib" / "three.min.js").is_file(), (
        "default-theme/assets/lib/three.min.js missing"
    )

    with tempfile.TemporaryDirectory() as _tmp:
        tmp = pathlib.Path(_tmp)
        partials = _make_partials(tmp)
        out_dir = tmp / "public"

        ctx = _build_minimal_ctx(out_dir, _DEFAULT_THEME_ASSETS, partials)
        written = engine.build(ctx, out_dir)

        # 1. Files written
        assert "index.html" in written, "index.html not written"
        assert any(w.startswith("pages/") for w in written), "no pages/*.html written"

        # Read output files
        index_html = (out_dir / "index.html").read_text(encoding="utf-8")
        page_files = list((out_dir / "pages").glob("*.html")) if (out_dir / "pages").is_dir() else []
        all_html = [index_html] + [f.read_text(encoding="utf-8") for f in page_files]

        # 2a. hero canvas#net present in index
        assert 'id="net"' in index_html or "id='net'" in index_html, (
            "canvas#net (hero shell) not found in index.html"
        )

        # 2b. lang-toggle buttons present
        assert 'id="btn-en"' in index_html, "btn-en (lang-toggle) not found in index.html"
        assert 'id="btn-vi"' in index_html, "btn-vi (lang-toggle) not found in index.html"

        # 2c. sidebar present — sidebar appears in pages/*.html (view-guide), not in the hub.
        #     Check single-file output OR the first interior page.
        single_file = out_dir / "vsf-aio-platform-showcase.html"
        if single_file.is_file():
            single_html = single_file.read_text(encoding="utf-8")
            assert "docs-side" in single_html, (
                "sidebar (.docs-side) not found in single-file output"
            )
        elif page_files:
            first_page = page_files[0].read_text(encoding="utf-8")
            assert "docs-side" in first_page, (
                "sidebar (.docs-side) not found in pages/*.html"
            )
        else:
            pytest.fail("No pages/*.html and no single-file — cannot check sidebar")

        # 3. No dangling @key@ tokens
        for i, html in enumerate(all_html):
            dangling = _ATKEY_RE.findall(html)
            assert not dangling, (
                f"Dangling @key@ tokens in HTML file {i}: {dangling}"
            )

        # 4. All <script src> + <link href> pointing to assets/ resolve to existing files
        for i, html in enumerate(all_html):
            for m in _SCRIPT_SRC_RE.finditer(html):
                src = m.group(1)
                if not src.startswith("assets/") and not src.startswith("../assets/"):
                    continue
                # Normalise relative path: ../assets/x -> assets/x (pages/ subdir)
                rel = src.replace("../assets/", "assets/")
                resolved = out_dir / rel
                assert resolved.is_file(), (
                    f"<script src> references missing file: {rel} (in HTML file {i})"
                )
            for m in _LINK_HREF_RE.finditer(html):
                href = m.group(1)
                if not href.startswith("assets/") and not href.startswith("../assets/"):
                    continue
                rel = href.replace("../assets/", "assets/")
                resolved = out_dir / rel
                assert resolved.is_file(), (
                    f"<link href> references missing file: {rel} (in HTML file {i})"
                )
